AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnvironmentName:
    Description: Name of the environment (test, prod etc)
    Type: String
  ApplicationName:
    Description: Name of the application
    Type: String
  PackageName:
    Description: The name of the bundled source code in the bucket
    Type: String

Resources:
  #The bucket the packaged source code will be in
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: BucketOwnerRead
      BucketName: !Join ['.', !Ref ApplicationName, 'source-bucket', !Ref EnvironmentName] 

  #The application
  Application:
      Type: AWS::ElasticBeanstalk::Application
      Properties:
        ApplicationName: !Ref ApplicationName 

  #Version
  AppVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref Application
      SourceBundle:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref PackageName

  #Environment      
  RustServerElasticBeanstalk:
    Type: AWS::ElasticBeanstalk::Environment
    Properties: 
      ApplicationName: !Ref ApplicationName
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: 'Docker AL2 version 3.2.4'

Outputs:
  EndPointURL:
    Value: !GetAtt RustServerElasticBeanstalk.EndpointURL
    Description: The endpoint to call the server from