AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketName:
    Description: Name of the bucket to create
    Type: String
  CertificateARN:
    Description: ARN of the certificate
    Type: String
  Alias:
    Description: custom domain name
    Type: String


Resources:
  # Create an S3 Bucket that serves a static website (i.e. React app)
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead # visitors need to be able to access the sie
      WebsiteConfiguration: # this makes the S3 Bucket a static website/app
        IndexDocument: index.html
        ErrorDocument: 404.html

  # Add a Bucket Policy that lets public visitors access the web app
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket # attach to bucket being created
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement: # lets the public access/view the contents of your Bucket, i.e. web app
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*' # wildcard, allow all requests
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref MyBucket, /*]]
  
  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Alias
        IPV6Enabled: true
        Enabled: true
        Origins:
          - Id: !Ref BucketName
            DomainName: !Select [1, !Split ["//", !GetAtt MyBucket.WebsiteURL]]
            CustomOriginConfig: 
                OriginProtocolPolicy: match-viewer
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Ref BucketName
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        PriceClass: PriceClass_All

Outputs:
  CloudfrontID:
    Value: !Ref cloudfrontDistribution
    Description: ID for the cloudfront distribution